updates:
  - directory: /
    open-pull-requests-limit: 16
    package-ecosystem: github-actions
    schedule:
      interval: daily
  - directory: /
    open-pull-requests-limit: 16
    package-ecosystem: npm
    schedule:
      interval: daily
version: 2
