jobs:
  coverage:
    name: Check code coverages on Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node }}
      - name: Upgrade npm
        run: npm install npm@latest -g
      - name: Setup modules
        run: npm ci
      - name: Check code coverages
        run: npm test
      - name: Archive code coverage report
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          name: code-coverage-report-${{ github.event.repository.name }}-${{ matrix.node }}
          path: coverage
    strategy:
      fail-fast: false
      matrix:
        node:
          - 22
          - 24
          - 26
name: Coverage
on:
  push:
    branches:
      - main

