jobs:
  example:
    name: Run an example on Node.js ${{ matrix.node }}
    outputs:
      result: ${{ steps.example.outputs.result }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - 20
          - 22
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Upgrade npm
        run: npm install npm@latest -g
      - name: Setup modules
        run: npm ci
      - name: Run an example
        run: npm start
name: Example
on:
  push:
    branches:
      - main
