name: test
on:
  push:
    branches: [ main ]
jobs:
  npm-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14.17.5', '16.13.0', '17.0.1' ]
    name: Test on Node.js ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Setup modules
        run: npm i
      - name: Test
        run: npm test
